### ISSUE TITLE
Animation File and Sequence Naming Inconsistency

### ISSUE THREAD

**Issue by DaBigJoe** [ObsidianSuite/ObsidianSuite#37]
Currently, animation files contain a name field that pertains to the name of the sequence. However, if the animation file is renamed, this field isn't changed, which can leads to inconsistent names being used to reference the animation. 

Therefore, the name field should be removed, and the name of the sequence should only be derived from the file name, thus removing any inconsistencies. Since all animations run from files, this can be done.

**Comment by cubex2** [comment]
Not all animations run from file. Transitions are dynamically created animations. I suggest to set the name of the animation when it is being added to the AnimationRegistry instead of loading it from nbt instead of removing the name field. This should solve the problem while allowing for animations that are not loaded from files.

**Comment by DaBigJoe** [comment]
That's true, I didn't consider transitions. I will implement it as you suggested.

**Comment by DaBigJoe** [comment]
Done, just needs closing on merge.

**Comment by DaBigJoe** [comment]
#56 closed, therefore this is closed!
